#!/usr/bin/env python
import rospy
from reconfigurable_hippo import smc



class TrackingControlNode(smc.SmcNode):
    def __init__(self, name):
        super(TrackingControlNode, self).__init__(name=name)


def main():
    node = TrackingControlNode("tracking_ctrl")
    node.run()


if __name__ == "__main__":
    main()
